CREATE TABLE [dbo].[PROCESSING.PRODUCT] (
    [Id]          UNIQUEIDENTIFIER NOT NULL,
    [OrderPadId]  UNIQUEIDENTIFIER NULL,
    [Name]        VARCHAR (75)     NOT NULL,
    [Value]       DECIMAL (25, 2)  NOT NULL,
    [Description] VARCHAR (100)    NULL,
    [Quantity]    INT              NOT NULL,
    CONSTRAINT [PK_PROCESSING.PRODUCT] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PROCESSING.PRODUCT_DOMAIN.ORDERPAD_OrderPadId] FOREIGN KEY ([OrderPadId]) REFERENCES [dbo].[DOMAIN.ORDERPAD] ([Id])
);


GO
CREATE NONCLUSTERED INDEX [IX_PROCESSING.PRODUCT_OrderPadId]
    ON [dbo].[PROCESSING.PRODUCT]([OrderPadId] ASC);

