// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pastelaria.ORM;

namespace Pastelaria.ORM.Migrations
{
    [DbContext(typeof(PastelariaDBContext))]
    [Migration("20220607194551_tt")]
    partial class tt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PASTELARIA")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrderPadProcessingProduct", b =>
                {
                    b.Property<Guid>("OrderPadsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProcessingProductsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderPadsId", "ProcessingProductsId");

                    b.HasIndex("ProcessingProductsId");

                    b.ToTable("OrderPadProcessingProduct");
                });

            modelBuilder.Entity("Pastelaria.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentityDocument")
                        .HasColumnType("VARCHAR(14)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(75)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("Id");

                    b.ToTable("DOMAIN.CUSTOMER");
                });

            modelBuilder.Entity("Pastelaria.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcessUser")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<int>("EmployeeActiveEnum")
                        .HasColumnType("INT");

                    b.Property<int>("EmployeePermissionsEnum")
                        .HasColumnType("INT");

                    b.Property<string>("IdentityDocument")
                        .IsRequired()
                        .HasColumnType("VARCHAR(14)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(75)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.HasKey("Id");

                    b.ToTable("DOMAIN.EMPLOYEE");
                });

            modelBuilder.Entity("Pastelaria.Domain.OrderPad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("DATE");

                    b.Property<Guid?>("OrderPadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderPadPaymentStatus")
                        .HasColumnType("INT");

                    b.Property<int>("OrderPadStatus")
                        .HasColumnType("INT");

                    b.Property<decimal>("Total")
                        .HasColumnType("DECIMAL");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrderPadId");

                    b.ToTable("DOMAIN.ORDERPAD");
                });

            modelBuilder.Entity("Pastelaria.Domain.ProcessingProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(75)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL");

                    b.HasKey("Id");

                    b.ToTable("PROCESSING.PRODUCT");
                });

            modelBuilder.Entity("Pastelaria.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(75)");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL");

                    b.HasKey("Id");

                    b.ToTable("DOMAIN.PRODUCT");
                });

            modelBuilder.Entity("OrderPadProcessingProduct", b =>
                {
                    b.HasOne("Pastelaria.Domain.OrderPad", null)
                        .WithMany()
                        .HasForeignKey("OrderPadsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pastelaria.Domain.ProcessingProduct", null)
                        .WithMany()
                        .HasForeignKey("ProcessingProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pastelaria.Domain.OrderPad", b =>
                {
                    b.HasOne("Pastelaria.Domain.Customer", "Customer")
                        .WithMany("OrderPads")
                        .HasForeignKey("CustomerId");

                    b.HasOne("Pastelaria.Domain.Employee", "Employee")
                        .WithMany("OrderPads")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Pastelaria.Domain.OrderPad", null)
                        .WithMany("OrderPads")
                        .HasForeignKey("OrderPadId");

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Pastelaria.Domain.Customer", b =>
                {
                    b.Navigation("OrderPads");
                });

            modelBuilder.Entity("Pastelaria.Domain.Employee", b =>
                {
                    b.Navigation("OrderPads");
                });

            modelBuilder.Entity("Pastelaria.Domain.OrderPad", b =>
                {
                    b.Navigation("OrderPads");
                });
#pragma warning restore 612, 618
        }
    }
}
